### PR TITLE
node labels being applied with business rules from help page enforced

### PR DESCRIPTION
**Pull request by DerekStrickland**
I'm new to Rust and krustlet, so forgive me if it's not spot on. Happy to take feedback and incorporate.  I think this effectively enforces the rules specified by the man page, and also handles building all mandatory labels in one functional chain.

### CODE REVIEW

**Comment by DerekStrickland** [comment]
I'm going to take a stab tomorrow morning at incorporating feedback from [PR 197](https://github.com/deislabs/krustlet/pull/197) into this one so we get the best of both our efforts.

**Comment by jingweno** [comment]
@DerekStrickland 👋 https://github.com/deislabs/krustlet/pull/197 is already ready to be merged. Why are you duplicating efforts?

**Comment by DerekStrickland** [comment]
@jingweno Hi!  As I commented [on the issue](https://github.com/deislabs/krustlet/issues/184#issuecomment-616172178), I started this yesterday, and was just testing before I submitted a PR this morning.  I wasn't trying to duplicate effort, so, sorry for that. It just seems we both decided to take a pass at the same time. You actually taught me a better way to handle the JSON merging that what I was doing so thanks for that! The main difference I think is that I tried to handle the prefix/allowed namespaces rules from the man pages, and created a builder function that combines the default, runtime, and arg provided labels all at once. Maybe I should wait for your PR to be merged and then branch and add my stuff?  cc'ing @thomastaylor312 to get maintainer input on how/whether to proceed.

**Comment by thomastaylor312** [comment]
@DerekStrickland Since you are building on top of the work in #197 I think we should review and merge that one and then you can rebase your work on top of that

**Comment by DerekStrickland** [comment]
@thomastaylor312  perfect.  Will do.

**Comment by bacongobbler** [comment]
Hi @DerekStrickland! #197 has now been merged. As a heads up, a few things were changed in the PR before it was merged so there might be a few things you'll need to tweak in this PR. Let us know when this is ready for another review.

Thanks again for your contribution!

**Pull request closed without merging**
