### PR TITLE
Clean-up phase in krator fixed where a channel was closed prematurely

### LINKED ISSUE #556: Channel in krator is closed prematurely
When a resource is deleted then krator logs the following warning:

```
[WARN  krator::runtime] Error dispatching object event. error=channel closed
```

The manifest receiver in `krator::runtime::run_object_task` is consumed on cleanup and the channel is closed ([krator/src/runtime.rs#L378](https://github.com/deislabs/krustlet/blob/v0.7.0/crates/krator/src/runtime.rs#L378)). The resource is deleted afterwards ([krator/src/runtime.rs#L396](https://github.com/deislabs/krustlet/blob/v0.7.0/crates/krator/src/runtime.rs#L396)) which emits an `Apply` event with the new `deletion_timestamp` and a `Deleted` event. When the `Apply` event is handled then the resource task is terminated because the "Manifest receiver hung up" ([krator/src/runtime.rs#L191-L192](https://github.com/deislabs/krustlet/blob/v0.7.0/crates/krator/src/runtime.rs#L191-L192)). When the `Deleted` event is handled then the warning is logged because the channel to the resource task is already closed.

A possible solution would be to clone the manifest receiver ([krator/src/runtime.rs#L378](https://github.com/deislabs/krustlet/blob/v0.7.0/crates/krator/src/runtime.rs#L378)):

```
match operator.deregistration_hook(manifest.clone()).await {
```

Then the resource task does not terminate prematurely, can process the `Deleted` event and terminates afterwards.

### PR DESCRIPTION
**Pull request by siegfriedweber**
Fixes #556

### CODE REVIEW

**Comment by kflansburg** [comment]
Thanks for catching this. It sounds like keeping the manifest object around until the end of `run_object_task` has fixed the issue for you, but I would expect there to still be a race condition here. Do you think that we should `await` at the end of `run_object_task` until the `Deleted` event arrives?

**Comment by siegfriedweber** [comment]
I am fairly new to Rust so treat my proposals with caution.

We have the following options:

- Do not send a manifest after the resource was deleted, i.e. remove [krator/src/runtime.rs#L207-L213](https://github.com/deislabs/krustlet/blob/v0.7.0/crates/krator/src/runtime.rs#L207-L213).
- Add another `Notify` channel, e.g. `resource_task_terminated` besides `deleted`, which is awaited at the end of `run_object_task`. The `deleted` channel is actually notified very often:
  - in the Running phase when the `deletion_timestamp` is applied
  - in the Terminated phase when the new status is applied
  - when the `run_object_task` deletes the resource and the `deletion_timestamp` without a grace period is applied
  - when the `Deleted` event is handled

**Comment by kflansburg** [comment]
I think its important that `Deleted` events get sent to the channel in case one arrives when Krator was not already shutting down. I think this happens when someone runs `kubectl delete --force --grace-period=0`. 

I think my suggestion was that `Manifest` would have a new method on it that allows you to `await` for it to be deleted.

**Comment by kflansburg** [comment]
@siegfriedweber Let me know what you think of my commit. I think your solution makes sense, I just want to make sure that the `Manifest` isn't dropped until the `Deleted` event is received. 

We now have a lot of `Notifies`, but I think that can be refactored later.

**Comment by siegfriedweber** [comment]
I fixed a copy&paste error and moved the notification of `deleted_event` after the manifest was sent.

**Review by kflansburg — APPROVED** [review]
LGTM

**Pull request merged**
