### PR TITLE
bump configurator to v0.0.5

### PR DESCRIPTION
**Pull request by bacongobbler**
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hmm... https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by radu-matei** [comment]
There is an underlying change in the libraries used by `configurator`.
I updated `setup-kind`, and I'll do the same with `configurator`, will comment here once there's a new release.

**Comment by radu-matei** [comment]
You can bump configurator to `v0.0.5` and remove any other environment variables.

https://github.com/engineerd/configurator/releases/tag/v0.0.5

**Comment by radu-matei** [comment]
You should also update 
https://github.com/engineerd/setup-kind/releases/tag/v0.5.0

**Comment by bacongobbler** [comment]
good call. done.

**Review by radu-matei — APPROVED** [review]

**Pull request merged**
