### PR TITLE
bump wascc-host to 0.10

### LINKED ISSUE #315: bump wascc-host to 0.10
There will be a wascc-host 0.10 release coming out later this week. When that's available we should bump to the next release and introduce lattice support (should be as easy as adding`features = ["lattice"]` to wascc-provider's Cargo.toml)

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #315

### CODE REVIEW

**Comment by bacongobbler** [comment]
Note: still have to test this with the demos; it's possible that the capability descriptors (ToActor, ToProvider) could introduce some breaking changes to the signed actors.

**Comment by bacongobbler** [comment]
unfortunately I'm blocked until wasi-common 0.19 is out. bumping to wascc-host 0.10 requires wasi-common 0.18 or higher, and we pinned to a commit in https://github.com/deislabs/krustlet/pull/319 to fix an issue with wasi-common 0.18.

Once wasi-common 0.19 has been released we can go and merge this.

**Comment by thomastaylor312** [comment]
@peterhuene Do you by chance have any info on when a 0.18.1 or 0.19 will be cut? I know you had mentioned you were looking into it before

**Comment by peterhuene** [comment]
I've raised the issue of publishing 0.19.0 and we're prepping for a release.  It may happen soon (today or tomorrow) unless there's more things that need to go in.

**Comment by thomastaylor312** [comment]
Awesome! Thank you for checking back @peterhuene

**Comment by peterhuene** [comment]
@thomastaylor312 The 0.19.0 `wasmtime` (and `wasi-common`) crates have now been published!

**Comment by thomastaylor312** [comment]
Awesome thanks! 

@bacongobbler I'll take care of updating first thing tomorrow

**Comment by thomastaylor312** [comment]
@bacongobbler #326 Will be merging soon and will unblock this. You should probably regenerate the lock file so that wascc-host pulls in 0.10.1, which also has the wasmtime 0.19, but it will work either way

**Comment by thomastaylor312** [comment]
Actually I went and took care of the rebase and lock regen (it was merge conflict anyway) @bacongobbler. Feel free to take a look and merge if you are ok with it

**Comment by bacongobbler** [comment]
LGTM. Thanks!

**Pull request merged**
