### PR TITLE
 Output CRD in moose example 

### PR DESCRIPTION
**Pull request by kesselborn**
(updated subject & description as dependencies were already updated and therefore the focus of this change is now limited to the crd output): 
It's handy to have this in the example program as it might not be apparent, that the CRD can be auto-generated if you are not familiar with the kube library yet.

Output that gets produced:

```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mooses.animals.com
spec:
  group: animals.com
  names:
    kind: Moose
    plural: mooses
    shortNames: []
    singular: moose
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      name: v1
      schema:
        openAPIV3Schema:
          description: "Auto-generated derived type for MooseSpec via `CustomResource`"
          properties:
            spec:
              properties:
                antlers:
                  type: boolean
                height:
                  format: double
                  type: number
                weight:
                  format: double
                  type: number
              required:
                - antlers
                - height
                - weight
              type: object
            status:
              nullable: true
              properties:
                message:
                  nullable: true
                  type: string
                phase:
                  enum:
                    - Asleep
                    - Hungry
                    - Roaming
                  nullable: true
                  type: string
              type: object
          required:
            - spec
          title: Moose
          type: object
      served: true
      storage: true
      subresources:
        status: {}

```

### CODE REVIEW

**Comment by kflansburg** [comment]
Hey Daniel, thanks for this and the kind words. We were planning to update these crates to their latest version in #480, which has unfortunately taken longer than we expected to land. Besides that, I think these changes look good. I will leave it to @thomastaylor312 to determine if this needs to be merged first. 

I can say that from my testing on another operator that I'm working on, simply bumping `kube-derive` to `0.44` in the dependent crate appears to resolve this problem and not cause any compatibility issues with Krator.

**Comment by kesselborn** [comment]
Cool.
As a work around I am currently using the forked repo. 

It's not high prio if it'll be updated with #480 anyways. It's just super handy if the crd gets created automatically + confusing if the `::crd()` function exports a non-functioning crd.

**Review by thomastaylor312 — DISMISSED** [review]
Thank you for doing this @kesselborn! @kflansburg I think the tokio stuff is gonna take a bit due to the fixes on Windows, so if you are ok with it, let's just merge this. That ok with you?

I'll hold out on merging until you respond

**Comment by thomastaylor312** [comment]
@kesselborn So I actually managed to get the tokio 1.0 stuff unblocked on Windows so it should be good to go soon and you can rebase on that

**Comment by kesselborn** [comment]
wow, good news!

**Comment by kflansburg** [comment]
Hey @kesselborn , we were finally able to merge Tokio 1.0 (and `kube` 0.48 with it). I'd still like to accept the changes related to `JSONSchema` and displaying the YAML if you are up for rebasing.

**Comment by kesselborn** [comment]
that's excellent news.
I rebased the code and adjusted the subject and description of the PR.
During rebasing I noticed that `crates/wasi-provider/Cargo.toml` still has `k8s-openapi = 0.9` instead of `k8s-openapi = 0.11`. I wasn't sure if this was on purpose so I left it.
I could smuggle it in this PR are create another PR if you like.

Cheers,
Daniel

**Review by kflansburg — APPROVED** [review]
Awesome, thanks Daniel! 

Looking at the `wasi-provider`, it actually seems like `k8s-openapi` isn't used anymore in that crate. I think you can remove it from `Cargo.toml` if you want to include that in this PR.

**Comment by kesselborn** [comment]
ok, done ;)

**Pull request merged**
