### PR TITLE
Implement workaround for LeaseSpec serialization issue.

### PR DESCRIPTION
**Pull request by peterhuene**
See #5 relating to the issue this attempts to workaround.

Rather than serialize a `LeaseSpec` which has a variable sized timestamp
formatting, this forces the timestamps to the six digits of subsecond precision
currently required by the k8s API.

### CODE REVIEW

**Comment by peterhuene** [comment]
Although it looks like to take the fix from `k8s-openapi` we might need to also bump `kube` and there's been breaking API changes from the version we're currently using.

**Comment by radu-matei** [comment]
I think the easiest way forward would be to update #40 to use this patch.

**Comment by rylev** [comment]
Let's land #40 first and then see where we are.

**Comment by thomastaylor312** [comment]
#40 is merged. I still think we should probably use this fix as I don't know when a new version of `kube` will be released and I don't think we should be using master just for this

**Comment by bacongobbler** [comment]
I'm +1 on going forward with merging this. Would it make sense to add an additional comment under `lease_spec_definition` to remove this code once we update k8s-openapi? That way in case it gets lost we can always reference back to this and pull it out safely.

**Comment by radu-matei** [comment]
Wait - why not update `k8s-openapi` to the revision that specifically fixes our issue?

**Comment by bacongobbler** [comment]
Oh! Is that release out now?

**Comment by radu-matei** [comment]
There isn't a release yet - but there is a fix in `master` that specifically solves our issue - https://github.com/Arnavion/k8s-openapi/commit/35cbddfeb26726bc1a0c882a40584c262fb53726

**Comment by bacongobbler** [comment]
Okay. I'm of the opinion that I'd like to have something that works so we can move forward and test things out on master. Once the new crate version is available, we can update krustlet and remove this section of code.

Does that seem fair?

**Comment by bacongobbler** [comment]
We could also pin to the master branch of `k8s-openapi`, but this seems a little less risky to introduce new issues.

**Comment by radu-matei** [comment]
Ok, then let's merge this now and update once the crate has a new release.

Thanks a lot, @peterhuene!

**Pull request merged**
