### PR TITLE
remove wasm and wasi crate dependencies

### PR DESCRIPTION
**Pull request by bketelsen**
wascc-provider doesn't need wasi or wasmtime deps.

### CODE REVIEW

**Comment by thomastaylor312** [comment]
I agree with @rylev here. There should only be a lock file at the top level

**Comment by bketelsen** [comment]
interesting.  OK removing!

**Comment by bketelsen** [comment]
> I agree with @rylev here. There should only be a lock file at the top level

There is a only cargo.lock at the top level, is that what you're suggesting I remove?

**Comment by thomastaylor312** [comment]
Oh, I misread that. Actually @rylev are you sure? Our top level has the need for a lock file due to the things we are building

**Comment by rylev** [comment]
@bketelsen sorry, misread the path. All is good!

**Pull request merged**
