### PR TITLE
Fix typo: AdmissionTLs -> AdmissionTLS

### PR DESCRIPTION
**Pull request by kesselborn**
Cases don't make sense that way ;) ... oversaw that one until I used it in a project

### CODE REVIEW

**Comment by kflansburg** [comment]
While I agree that it’s not correct English, the partially lowercase acronym is idiomatic Rust. If you run clippy on your branch, it should complain about the all uppercase acronym.

**Comment by kesselborn** [comment]
But then it should at least bei AdmissionTls, nicht AdmissionTLs

Making TLS all capital is probably something I got from Go.
Either way is fine, but not TLs

**Comment by bacongobbler** [comment]
@kesselborn im not sure where you see it as AdmissionTLs.If you look at the code more closely the L is lowercases to follow Rust’s convention of AdmissionTls. Please re-review more closely :)

From https://doc.rust-lang.org/1.0.0/style/style/naming/README.html:

> In CamelCase, acronyms count as one word: use Uuid rather than UUID. In snake_case, acronyms are lower-cased: is_xid_start.

This follows Rust’s convention, so the current casing is correct. Because of that I’m going ahead and closing this as the current styling confirms to standard Rust style convention.

**Comment by kesselborn** [comment]
Uhm 🙈,
super sorry: I should sleep more 😀

I was 100% convinced that it was wrong but looking a the change proves me kind of wrong 😃

Sorry for the noise, don’t know what was wrong with me this morning.

Cheers,
Daniel

**Pull request closed without merging**
