### PR TITLE
Remove unused flags from howto guides

### PR DESCRIPTION
**Pull request by jiayihu**
Just finishing the removal started in #447 because I had the same issue because of the flags

### CODE REVIEW

**Comment by itowlson** [comment]
@thomastaylor312 We still invoke using these flags in the justfile - should they stay in the docs or go as this PR suggests?

**Comment by kflansburg** [comment]
This still controls *where* the certs are written by Krustlet during bootstrapping. The user was confused because the bootstrap script does not create these files and so they were not there prior to the first run of Krustlet. I agree that this is probably a little confusing to have in the beginner documentation. FWIW, I still use these all the time, as they are key if you plan on running bot wasi and wascc at the same time.

**Comment by jiayihu** [comment]
For me it wasn't just confusing, it actually gave errors when launching the command as shown by another user in https://github.com/deislabs/krustlet/issues/447#issuecomment-724946954 and for a quick-start documentation it's not helpful at all. If it is still useful it should be left as note maybe.

**Comment by kflansburg** [comment]
The error that you linked to seems to be due to it not finding bootstrap.conf, and not the certificates. It isnt clear to me why this happened.

**Comment by thomastaylor312** [comment]
I think that taking these out of the beginner docs is good, but we should leave examples of them documented in other places

**Comment by bacongobbler** [comment]
agree on ^^. Let's go ahead and merge this and follow up as needed. A topic page dedicated to krustlet's feature flags would be a good start.

**Pull request merged**
