### PR TITLE
Add DigitalOcean|LKE docs to index

### PR DESCRIPTION
**Pull request by DazWilkin**
Updates are out-of-sync w/ PRs but consistent with them:

+ DigitalOcean (#496)
+ Linode (#497)

### CODE REVIEW

**Review by thomastaylor312 — APPROVED** [review]
Good to go once all dependent PRs are merged

**Comment by thomastaylor312** [comment]
@DazWilkin You want to update this so it just contains the Digital Ocean instructions?

**Comment by DazWilkin** [comment]
> @DazWilkin You want to update this so it just contains the Digital Ocean instructions?

I should probably delete the DigitalOcean instructions too.

Those also use publicly accessible machines.

**Comment by DazWilkin** [comment]
See: https://github.com/deislabs/krustlet/pull/535

**Pull request closed without merging**
