### PR TITLE
Lint docs for all PRs and branches

### LINKED ISSUE #493: Update tests to run markdown lint for docs path changes.

### PR DESCRIPTION
**Pull request by kflansburg**
It doesn't appear to be possible to skip some jobs based on what paths were updated, so I split lints out into a new Action that runs for everything. 

cc #490 
Closes #493

### CODE REVIEW

**Comment by bacongobbler** [comment]
Right now we have a `paths-ignore` rule in build.yaml so we don't run tests on doc changes. Should we opt to remove that and instead add a `paths` rule in lint.yaml for any doc changes?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by bacongobbler** [comment]
image

**Comment by kflansburg** [comment]
Ah, I did not see the paths directive, that's exactly what I was looking for! I will give that a shot.

**Comment by kflansburg** [comment]
Ok @bacongobbler I think this is ready.

**Comment by thomastaylor312** [comment]
This is looking good to me, I just have one question. So as it stands this looks like what happens:

1. Any change to code (including docs changes) will trigger a full test run
2. Any change to stuff within `docs/` will trigger 1 additional lint pass

So are we going to require PRs to have passing doc lint tests? If that is the case, then when a PR does not include docs changes, it will end up with one "hanging" test every time. How do we want to handle that?

**Comment by kflansburg** [comment]
Can we merge this soon? #514 introduced more failing documentation.

**Comment by kflansburg** [comment]
> So are we going to require PRs to have passing doc lint tests? If that is the case, then when a PR does not include docs changes, it will end up with one "hanging" test every time. How do we want to handle that?

My hope is that these tests do not show in the UI as hanging. If it does, then I say we just run everything for all PRs.

**Review by thomastaylor312 — APPROVED** [review]

**Pull request merged**
