### PR TITLE
check docs against markdownlint

### PR DESCRIPTION
**Pull request by bacongobbler**
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Review by thomastaylor312 — APPROVED** [review]
Good to go pending rebase

**Comment by kflansburg** [comment]
@bacongobbler @thomastaylor312  I've rebased, linted a few more files, and added linting to the CI process. Let me know what you think.

**Review by thomastaylor312 — APPROVED** [review]
Thanks for handling this @kflansburg. Let’s make sure @bacongobbler sees this and approves before merge because it is his PR

**Comment by bacongobbler** [comment]
LGTMing my own PR

**Pull request merged**
